export const languagesArray = [
    "English",
    "Spanish",
    "Chinese",
    "Korean",
    "Japanese", 
    "French",
    "Portuguese",
    "German",
    "Russian",
    "Indonesian",
    "Arabic",
    "Hindi",
    "Latin",
    "Sanskrit",
];