export const majorsArray = [
"Aerospace Engineering",
"Anthropology (Archaeology)",
"Anthropology (Biological Anthropology)",
"Anthropology (Sociocultural Anthropology)",
"Anthropology with a Concentration in Climate Change and Human Solutions",
"Art History / Criticism",
"Biochemistry and Cell Biology",
"Biochemistry",
"Bioengineering (Bioinformatics)",
"Bioengineering (Biotechnology)",
"Bioengineering",
"Bioengineering: BioSystems",
"Biological Anthropology",
"Biology with Specialization in Bioinformatics",
"Business Psychology",
"Chemical Engineering",
"Chemistry",
"Chinese Studies",
"Classical Studies",
"Cognitive Science with Specialization in Clinical Aspects of Cognition",
"Cognitive Science with Specialization in Design and Interaction",
"Cognitive Science with Specialization in Language and Culture",
"Cognitive Science with Specialization in Machine Learning and Neural Computation",
"Cognitive Science with Specialization in Neuroscience",
"Cognitive and Behavioral Neuroscience",
"Communication",
"Computer Engineering",
"Computer Science with Specialization in Bioinformatics",
"Computer Science",
"Critical Gender Studies",
"Dance",
"Data Science",
"Earth Sciences",
"Ecology, Behavior and Evolution",
"Economics and Mathematics",
"Economics",
"Economics-Public Policy",
"Education Sciences",
"Electrical Engineering and Society",
"Electrical Engineering",
"Engineering Physics",
"Environmental Chemistry",
"Environmental Engineering",
"Environmental Systems (Earth Sciences)",
"Environmental Systems (Ecology, Behavior, & Evolution)",
"Environmental Systems (Environmental Chemistry)",
"Environmental Systems (Environmental Policy)",
"Ethnic Studies",
"General Biology",
"General Physics",
"General Physics/ Secondary Education",
"German Studies",
"Global Health",
"Global South Studies",
"History",
"Human Biology",
"Human Developmental Sciences with a Specialization in Equity and Diversity",
"Human Developmental Sciences with a Specialization in Healthy Aging",
"Human Developmental Sciences",
"Interdisciplinary Computing and the Arts",
"International Studies - Anthropology",
"International Studies - Economics",
"International Studies - History",
"International Studies - International Business",
"International Studies - Linguistics",
"International Studies - Literature",
"International Studies - Political Science",
"International Studies - Sociology",
"Italian Studies",
"Japanese Studies",
"Jewish Studies",
"Latin American Studies with a Concentration in Mexico",
"Latin American Studies with a Concentration in Migration and Border Studies",
"Latin American Studies",
"Linguistics (Specialization in Cognition and Language)",
"Linguistics (Specialization in Language and Society)",
"Linguistics (Specialization in Speech and Language Sciences)",
"Linguistics",
"Linguistics: Language Studies (Specialization in Individual Language)",
"Literature/Writing",
"Literatures in English",
"Management Science",
"Marine Biology",
"Mathematics - Applied",
"Mathematics - Computer Science",
"Mathematics - Scientific Computation",
"Mathematics - Secondary Education",
"Mathematics and Economics - Joint Major",
"Mathematics",
"Mechanical Engineering with a Specialization in Controls and Robotics",
"Mechanical Engineering with a Specialization in Fluid Mechanics and Thermal Systems",
"Mechanical Engineering with a Specialization in Materials Science and Engineering",
"Mechanical Engineering with a Specialization in Mechanics of Materials",
"Mechanical Engineering with a Specialization in Renewable Energy and Environmental Flows",
"Mechanical Engineering",
"Media",
"Microbiology",
"Molecular Biology",
"Molecular Synthesis",
"Molecular and Cell Biology",
"Music Humanities",
"Music",
"NanoEngineering",
"Neurobiology",
"Oceanic and Atmospheric Sciences",
"Pharmacological Chemistry",
"Philosophy",
"Physics - Biophysics",
"Physics with Specialization in Astrophysics",
"Physics with Specialization in Computational Physics",
"Physics with Specialization in Earth Sciences",
"Physics with Specialization in Materials Physics",
"Physics",
"Physiology and Neuroscience",
"Political Science (American Politics)",
"Political Science (Comparative Politics)",
"Political Science (Data Analytics)",
"Political Science (International Affairs)",
"Political Science (International Relations)",
"Political Science (Political Theory)",
"Political Science (Public Law)",
"Political Science (Public Policy)",
"Political Science (Race, Ethnicity, and Politics)",
"Political Science",
"Probability and Statistics",
"Psychology with a Specialization in Clinical Psychology",
"Psychology with a Specialization in Cognitive Psychology",
"Psychology with a Specialization in Developmental Psychology",
"Psychology with a Specialization in Human Health",
"Psychology with a Specialization in Sensation and Perception",
"Psychology with a Specialization in Social Psychology",
"Psychology",
"Public Health",
"Real Estate and Development",
"Sociology - American Studies",
"Sociology - Culture and Communication",
"Sociology - Economy and Society",
"Sociology - International Studies",
"Sociology - Law and Society",
"Sociology - Science and Medicine",
"Sociology - Social Inequality",
"Spanish Literature",
"Speculative Design",
"Structural Engineering",
"Studio",
"Study of Religion",
"Theatre",
"Undeclared - Humanities/Arts",
"Undeclared - Physical Sciences",
"Undeclared - Social Sciences",
"Urban Studies and Planning",
"World Literature and Culture", 
]
